In [2]:
from sklearn.feature_extraction import DictVectorizer
dict = DictVectorizer(sparse=False)
data = dict.fit_transform([{'city': '北京','temperature': 100},
                           {'city': '上海','temperature':60},
                            {'city': '深圳','temperature': 30}])
print(data)  # ['city=上海', 'city=北京', 'city=深圳', 'temperature']
print(dict.get_feature_names())
print(dict.inverse_transform(data))

[[  0.   1.   0. 100.]
 [  1.   0.   0.  60.]
 [  0.   0.   1.  30.]]


AttributeError: 'DictVectorizer' object has no attribute 'get_feature_names'

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
#实例化CountVectorizer()
vector = CountVectorizer()
#调用fit_transform输入并转换数据
res = vector.fit_transform(["life is short,i like python",
                            "life is too long,i dislike python"])
# 获取特征值
print(vector.get_feature_names())
# 转换后的数据
print(res.toarray())

AttributeError: 'CountVectorizer' object has no attribute 'get_feature_names'

In [4]:
from sklearn.feature_selection import VarianceThreshold
#实例化VarianceThreshold()
var = VarianceThreshold()
#调用fit_transform()输入并转换数据
data = var.fit_transform([[0,2,0,3],
                      [0,1,4,3],
                      [0,1,1,3]])
#转换后的数据
print(data)

[[2 0]
 [1 4]
 [1 1]]


In [8]:
from sklearn.preprocessing import MinMaxScaler
#实例化MinMaxScaler()
mm = MinMaxScaler()
# 调用fit_transform()输入并转换数据
data = mm.fit_transform([[90,2,10,40],[60,4,15,45],[75,3,13,46]])
# 转换后的数据
print(data)

[[1.         0.         0.         0.        ]
 [0.         1.         1.         0.83333333]
 [0.5        0.5        0.6        1.        ]]


In [9]:
from sklearn.preprocessing import StandardScaler
#实例化StandardScaler()
standard = StandardScaler()
#调用fit_transform()输入并转换数据
data = standard.fit_transform([[1,-1,3],[2,4,2],[4,6,1]])
#转换后的数据
print(data)

[[-1.06904497 -1.35873244  1.22474487]
 [-0.26726124  0.33968311  0.        ]
 [ 1.33630621  1.01904933 -1.22474487]]


In [10]:
from sklearn.preprocessing import Imputer
from sklearn.impute import SimpleImputer
import numpy as np
#实例化SimpleImputer(),指定缺失值为missing_values=np.NaN,
# 填补策略为平均值strategy="mean"
im = SimpleImputer(missing_values=np.NaN,strategy="mean")
# 调用fit_transform()输入并转换数据
data = im.fit_transform([[1,2],[np.NaN,3],[7,6]])
# 转换后的数据
print(data)

ImportError: cannot import name 'Imputer' from 'sklearn.preprocessing' (E:\Python\python3.12.0\Lib\site-packages\sklearn\preprocessing\__init__.py)